### ISSUE TITLE
TiRa Koodikatselmointi #1

### ISSUE THREAD

**Issue by jjanii** [Aapzu/super-duper-pentago#3]
Ohjelma ladattu  11.2 klo 23.00

Ohjelma on mielestäni jaettu selvästi eri luokkiin, ja luokat ovat nimetty hyvin niiden tehtäviä vastaaviksi. Pidin myös siitä, että luokat sisälsivät juuri omat tehtävät eikä yhtään mitään ylimääräistä. Pientä haastavuutta koodin lukemiseen tuli se, etten ole täysin varma mitä olet javalabran aikana ohjelmaan jo tehnyt, ja mitkä ovat 'uusia' tiralabraa varten tehtyjä luokkia (tai oletko muokannut vanhoja luokkia).

Koodin lukeminen ei tuottanut vaikeuksia, ehkä kommentointia olisi voinut joissain kohdin lisätä koodinlukua vielä lisää selkeyttämään. Kuitenkin pääpointit tuli hyvin selville niin luokkien ja metodien nimistä sekä lyhyehköistä kommenteista (monissa kohdin kommentointi oli myös hyvin kattavaa). Koodin olisi kuitenkin joissain kohdissa jakaa useampiin metodeihin, esimerkiksi luokan **PossibleGamesWithOneMove** metodi get sisältää 5 for looppia päällekkäin, ja sen olisi voinut jakaa muutamaan metodiin selkeyttämään toimintaa. 

Muistaakseni myös try-catcheja ei saisi/suositeltaisi olemaan päällekkäin, joka sekin tapahtuu tuossa **PossibleGamesWithOneMove** luokan get metodissa. Pohdin myöskin jos ko. luokan voisi nimetä jollakin muulla nimellä, koska mielestäni tuo nimi kuulostaa enemmän metodin nimeltä (tämä tosin vain minun mielipiteeni). Myös exceptionien catchit taisi olla kaikissa luokissa vain nimellä "ignore" eikä esimerkiksi niistä välitetty sen enempää, joku error message voisi olla kohdallaan mikäli sellaiselle olisi käyttöä(?)

Projekti on kaikinpuolin hyvin toteutettu, ja peliä pelatessani tekoäly hoiti myös hyvin hommansa minua vastaan pelatessani. Ohjelma vaikuttaa hyvin laajalta, toki se sisältää myös javalabran mutta silti ohjelma on vaatinut varmasti huomattavan paljon pohtimista sekä aikaa. Ohjelma vaikutti mielestäni valmiilta pelin toiminnallisuuksien suhteen, omia tietorakenteita et nähtävästi vielä ollut päässyt aloittamaan, mutta uskoisin että ne eivät ole iso ongelma enään verrattuna muutoin tuohon projektiin.

**Comment by aapzu** [comment]
Kiitos!
Tuo **PossibleGamesWithOneMove** on tosiaan hirvitys, ja se onkin muuttunut kokonaan tällä viikolla. Muuten otan kommenttisi huomioon jatkokehityksessä.
